### ISSUE TITLE
Play m4a?

### ISSUE THREAD

**Issue by echarlie** [wuvt/johnny-six#18]
Usually, this is a container format for mp3; Dr. Sue commented that they were not playing, but theoretically, we should be able to decode and handle them.

**Comment by mutantmonkey** [comment]
Usually m4a is used for AAC, not MP3. We're building with FAAD, so m4a files should play but I can pull the logs and see. Would it be possible to get a timestamp?

**Comment by echarlie** [comment]
check pload playlist archive.

**Comment by echarlie** [comment]
@mutantmonkey says "it's an issue with linx's mime-type detection, I get content-type: video/mp4 for that m4a file [linked via linx]"

We should verify that johnny-six (read: liquidsoap) correctly read mp4 tags. Mutagen doesn't remove the `----:com.apple.iTunes` prefix.

**Comment by mutantmonkey** [comment]
This is fixed on the johnny-six side now by enabling the ffmpeg decoder, which happened when we moved to the official Liquidsoap Docker image in #19.

Liquidsoap has a pretty limited number of MIME types that it actually supports by default (https://github.com/savonet/liquidsoap/blob/129edff6d20e835221228a2f1932a9a4eae2d7b5/libs/protocols.liq#L202); with a fallback decoder (i.e. ffmpeg or GStreamer), it supports much more.
