### ISSUE TITLE
underwriting should have human-readable config

### ISSUE THREAD

**Issue by echarlie** [wuvt/johnny-six#7]
current yml config for underwriting is awful. write a new one.
it should store/allow
- [x] start and end dates
- [x] arbitrary metadata about underwriting (e.g. transcripts)
- [x] multiple recordings for each underwriting
- [ ] multiple underwriters per hour

Ideally, underwriting will play every underwriter for a given hour, and will select a random underwriting recording if there are multiple for a single piece of underwriting. It also should verify that it is before the end date and after the start date, so that we don't need to babysit underwriting. Some less useful potential features: use liquidsoap's built-in `say` support to read transcripts, if we have no recording of the underwriting.

Long-term, it may be possible to adapt this, with minimal modifications, to use for scheduled PSAs, Promos, and Rotation.

**Comment by telnoratti** [comment]
I would suggest that as much as possible of the properties be as optional. It will make onboarding new underwriting config writers easier as a simple config may consist of:

    bear_hunting:
      day: Monday
      block: 12-14
      files:
        - homemade/bearhunting.flac

An interesting idea might be to add a kind field so we can specify if it is a PSA or underwriting since these share much of the same metadata.

**Comment by echarlie** [comment]
My current example is in https://github.com/wuvt/johnny-six/blob/readable_underwiting/sample_underwriting.yml (exerpt is below) and example code for parsing that format (still in need of some cleaning) is in that same branch.

I agree that more of them should be optional; it does leave open the question of how we handle things like `startdate` and `enddate` when not present (do we not play the underwriting, or do we treat this as equivalent to do-not-kill?)

    - sponsor: nrv mall
      underwriting:
              - name: back to school
                startdate: 2017-07-03
                enddate: 2017-08-20
                transcript: --- >
                        I'm going to put a sample fake transcript into this for
                        fun because it could be useful
                url:
                        - https://example.com/underwiting/today.mp3
                        - https://example.com/underwiting/tomorrow.flac
                schedule:
                        monday: [0,1,2,3,4,5]
                        tuesday: [0,3,4,23,8]

One thing I don't like about your example is that `day` should probably be a list, and `block` is not as easily parsed. The problem with the current format is that a lot of effort is lost to duplicate the file list for each hour and each day; your example limits that duplicated effort to just for each block, but some underwriters will purchase several non-contiguous blocks of underwriting on several different days.

I also think it is useful to store all of the pieces of underwriting sponsored by a single entity under a header. If we were to use the *same* format for PSAs, it would allow us to see over the time between purging the file who is sponsoring PSAs a lot, and which PSAs are added regularly.

**Comment by telnoratti** [comment]
I would treat it as do-not-kill. We want the fallback to be human automation so if something breaks or something goes bonkers, less skilled humans can triage the situation. This is a general rule of thumb for any automation. My example was just an example, try working from your format to meet the requirements.

Why is it useful to aggregate sponsor underwriting? Does a single sponsor frequently have more than one underwriting message? This shouldn't be the canonical history of underwriting, but a configuration for current underwriting. There are much better formats for canonical listings.

**Comment by echarlie** [comment]
I think that historically, it was common for an underwriter to have 2 or more different scripts that were show/genre-specific, especially during radiothon. My expectation is that this file won't be rotated regularly, so having a format that aggregates by sponsor keeps it readable and provides better structure to the data than including a key/value in the underwriting.

It certainly wouldn't be unreasonable to store sponsor as a key/value under each item of underwriting (it would likely simplify parsing), but I think it makes it more apparent who our sponsors are, and how much underwriting/PSAs they ask us to read.

**Comment by telnoratti** [comment]
I think that's false in re multiple scripts. What is the value from an automation perspective to tracking underwriting by owner? What does that metadata add? If it has no value, then it should be excluded from the config. Remember it might have value to track from a business and operational perspective that is independent from automation.

**Comment by mutantmonkey** [comment]
I'm really in favor of replacing the underwriting with a web service in lieu of this. It will be more maintainable to just have the underwriting queue thing make an HTTP request to the web service to determine what needs to be queued.

**Comment by echarlie** [comment]
the current format, in 58aaa21fb63e331dcab48c9f3c2a85fac2efac9f removes the outermost list and dict from the yaml format, to simplify things; it may still be useful to track sponsors (for logging purposes), however, subdividing it by owner is probably unnecessary.
